name: minirt_CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v7

            - name: Install X11
              run: |
                sudo apt-get update
                sudo apt-get install gcc make xorg libxext-dev libbsd-dev

            - name: run make
              run: make
            
            - name: Norminette
              uses: 42School/norminette@3.3.59
              with:
                args: src/ includes/ '-RCheckForbiddenSourceHeader'